kbList: course_list

# Course
cdmc: room_name
dateDigitSeparator: update_date
jcs: periods
jxbmc: class_name
jxbzc: class_compose
kcmc: name
kcxz: course_type
khfsmc: exam_type
xf: credit
xm: teacher_name
xqj: weekday
xqmc: zone
xsdm: form_code
zcd: weeks
